# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12.9"
  RYE_VERSION: "0.44.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_VERSION=${{ env.RYE_VERSION }} RYE_INSTALL_OPTION="--yes" bash
    
    - name: Add Rye to PATH
      run: echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Install dependencies
      run: rye sync

    - name: Lint with pylint
      run: |
        rye run lint

    - name: Test with pytest
      run: |
        export PYTHONPATH=src/:$PYTHONPATH
        rye run test
        
    - name: Format code
      run: |
        rye run format-check
